FROM fcrepo/fcrepo:6.5.1-tomcat9 AS base

COPY ./fedora/config/activemq.xml /usr/local/tomcat/conf/activemq.xml

FROM golang:1.24 AS setup

WORKDIR /src

RUN git clone https://github.com/gwu-libraries/fedora_queue_test.git

RUN cd fedora_queue_test && go mod tidy && go build -o /bin/test-fedora-queue ./main.go

FROM base AS development

RUN mkdir /usr/local/test

COPY --from=setup /bin/test-fedora-queue /usr/local/test/

COPY --from=setup /src/fedora_queue_test/test-data  /usr/local/test/
