# Requires Docker Compose v2
name: scholarspace-dev

services:
  rails:
    image: scholarspace-rails:${RAILS_TAG:-latest}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_ENV=dev
        - BUNDLE_GEMFILE=Gemfile
    # i don't know that the bundle check || bundle install portion is needed anymore, 
    # but it is a fallback that installs gems if they aren't already installed, though
    # they should be as part of Dockerfile
    command: sh -lc 'bundle check || bundle install; yarn build:dev; bundle exec rails db:prepare; bundle exec rails db:seed; exec ./bin/rails server -p 3000 -b 0.0.0.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: always
    stdin_open: true
    user: ${APP_UID:-1001}:${APP_GID:-101}
    tty: true
    env_file:
      - .env
    environment:
      - RAILS_ROOT=/app/scholarspace
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true # webpacker autorefresh
    ports:
      - "3000:3000"
    volumes:
      - .:/app/scholarspace
      - storage:/app/scholarspace/storage
      - uploads:/app/scholarspace/uploads
      - tmp:/app/scholarspace/tmp
      - solr-ocr-index-cache:/.cache/solr-ocr-index-cache
      - whispercpp-cache:/.cache/whispercpp
    depends_on:
      app-volumes-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      solr:
        condition: service_healthy
      fedora:
        condition: service_healthy
      fits:
        condition: service_started
      memcached:
        condition: service_started

  worker:
    stdin_open: true
    tty: true
    image: scholarspace-worker:${RAILS_TAG:-latest}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_ENV=dev
        - BUNDLE_GEMFILE=Gemfile
    command: sh -lc 'bundle check || bundle install; exec bundle exec sidekiq'
    restart: always
    user: ${APP_UID:-1001}:${APP_GID:-101}
    env_file:
      - .env
    environment:
      - RAILS_ROOT=/app/scholarspace
      - RAILS_ENV=development
    depends_on:
      app-volumes-init:
        condition: service_completed_successfully
      rails:
        condition: service_healthy
    volumes:
      - .:/app/scholarspace
      - storage:/app/scholarspace/storage
      - uploads:/app/scholarspace/uploads
      - tmp:/app/scholarspace/tmp
      - solr-ocr-index-cache:/.cache/solr-ocr-index-cache
      - whispercpp-cache:/.cache/whispercpp

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl
    restart: always
    depends_on:
      rails:
        condition: service_healthy

  solr:
    ports:
      - "62821:8983"
    command:
      - sh
      - "-c"
      - "precreate-core scholarspace_test /opt/solr/server/configsets/hyraxconf; solr-precreate scholarspace_dev /opt/solr/server/configsets/hyraxconf"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  memcached:
    ports:
      - "11211:11211"

  fedora:
    ports:
      - "8080:8080"

  fits:
    ports:
      - "8081:8081"

volumes:
  node_modules:

networks:
  default:
    name: scholarspace-dev-net
