ARG ALPINE_VERSION=3.21
ARG RUBY_VERSION=3.3.6

FROM ruby:$RUBY_VERSION-alpine$ALPINE_VERSION AS scholarspace-prod-base

ARG DATABASE_APK_PACKAGE="postgresql-dev"
ARG EXTRA_APK_PACKAGES="git"
ARG RUBYGEMS_VERSION=""

RUN addgroup -S --gid 101 app && \
    adduser -S -G app -u 1001 -s /bin/sh -h /app app

RUN apk --no-cache upgrade && \
  apk --no-cache add acl \
  build-base \
  curl \
  gcompat \
  imagemagick \
  imagemagick-heic \
  imagemagick-jpeg \
  imagemagick-jxl \
  imagemagick-pdf \
  imagemagick-svg \
  imagemagick-tiff \
  imagemagick-webp \
  jemalloc \
  ruby-grpc \
  tzdata \
  nodejs \
  yarn \
  zip \
  $DATABASE_APK_PACKAGE \
  $EXTRA_APK_PACKAGES

RUN setfacl -d -m o::rwx /usr/local/bundle && \
  gem update --silent --system $RUBYGEMS_VERSION

USER app

RUN mkdir -p /app/scholarspace
WORKDIR /app/scholarspace
# COPY --chown=1001:101 ./bin/*.sh /scholarspace/bin

ENV PATH="/app/scholarspace:$PATH" \
RAILS_ROOT="/app/scholarspace" \
RAILS_SERVE_STATIC_FILES="1" \
LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"

COPY Gemfile Gemfile.lock ./

RUN bundle config set without development test 

RUN bundle config set deployment true 

RUN bundle install

COPY --chown=1001:101 . ./

COPY --chmod=755 ./bin/scholarspace-entrypoint-prod.sh ./

RUN yarn install

FROM scholarspace-prod-base AS scholarspace-prod

ENTRYPOINT ["./scholarspace-entrypoint-prod.sh"]
ONBUILD RUN RAILS_ENV=production bundle exec rake assets:precompile
CMD ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0", "RAILS_ENV=production"]

FROM scholarspace-prod-base AS scholarspace-prod-worker

USER root
RUN apk --no-cache add bash \
  ffmpeg \
  mediainfo \
  openjdk17-jre \
  perl \
  tesseract-ocr
USER app

CMD ["bundle", "exec", "sidekiq", "RAILS_ENV=production"]