ARG ALPINE_VERSION=3.21
ARG RUBY_VERSION=3.3.6

FROM ruby:$RUBY_VERSION-alpine$ALPINE_VERSION AS scholarspace-dev-base

ARG RUBYGEMS_VERSION=""

RUN addgroup -S --gid 101 app && \
    adduser -S -G app -u 1001 -s /bin/sh -h /app app

RUN apk --no-cache upgrade && \
  apk --no-cache add acl \
  build-base \
  curl \
  gcompat \
  imagemagick \
  imagemagick-heic \
  imagemagick-jpeg \
  imagemagick-jxl \
  imagemagick-pdf \
  imagemagick-svg \
  imagemagick-tiff \
  imagemagick-webp \
  jemalloc \
  ruby-grpc \
  tzdata \
  nodejs \
  yarn \
  zip \
  tesseract-ocr \
  tesseract-ocr-data-eng \
  postgresql-dev \
  git \
  poppler-utils \
  libxml2 \
  libxml2-dev

RUN setfacl -d -m o::rwx /usr/local/bundle && \
  gem update --silent --system $RUBYGEMS_VERSION

USER app

RUN mkdir -p /app/scholarspace
WORKDIR /app/scholarspace
# COPY --chown=1001:101 ./bin/*.sh /scholarspace/bin

ENV PATH="/app/scholarspace:$PATH" \
RAILS_ROOT="/app/scholarspace" \
RAILS_SERVE_STATIC_FILES="1" \
LD_PRELOAD="/usr/local/lib/libjemalloc.so.2" 

RUN yarn install

COPY --chown=1001:101 ./vendor/iiif_print ./vendor/iiif_print

COPY --chown=1001:101 Gemfile Gemfile.lock ./

RUN git config --global --add safe.directory /app/scholarspace/vendor/iiif_print

RUN bundle config set deployment true 

RUN bundle install

COPY --chown=1001:101 . ./

COPY --chmod=755 ./bin/scholarspace-entrypoint-dev.sh ./

FROM scholarspace-dev-base AS scholarspace-dev

ENTRYPOINT ["./scholarspace-entrypoint-dev.sh"]
ONBUILD RUN RAILS_ENV=development SECRET_KEY_BASE=`bin/rake secret` bundle exec rake assets:precompile
CMD ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0", "RAILS_ENV=development"]

FROM scholarspace-dev-base AS scholarspace-dev-worker

USER root
RUN apk --no-cache add bash \
  ffmpeg \
  mediainfo \
  openjdk17-jre \
  perl \
  tesseract-ocr
USER app

CMD ["bundle", "exec", "sidekiq", "RAILS_ENV=development"]