ARG ALPINE_VERSION=3.21
ARG RUBY_VERSION=3.3.6

FROM ruby:$RUBY_VERSION-alpine$ALPINE_VERSION AS scholarspace-dev-base

ARG RUBYGEMS_VERSION=""

RUN addgroup -S --gid 8983 app && \
    adduser -S -G app -u 8983 -s /bin/sh -h /app app

RUN apk --no-cache upgrade && \
  apk --no-cache add acl \
  build-base \
  curl \
  gcompat \
  vips \
  imagemagick \
  imagemagick-heic \
  imagemagick-jpeg \
  imagemagick-jxl \
  imagemagick-pdf \
  imagemagick-svg \
  imagemagick-tiff \
  imagemagick-webp \
  jemalloc \
  ruby-grpc \
  tzdata \
  nodejs \
  yarn \
  zip \
  tesseract-ocr \
  tesseract-ocr-data-eng \
  postgresql-dev \
  git \
  poppler-utils \
  libxml2 \
  libxml2-dev \
  python3 \ 
  py3-pip \
  ocrmypdf \
  cmake

RUN setfacl -d -m o::rwx /usr/local/bundle && \
  gem update --silent --system $RUBYGEMS_VERSION

USER 8983:8983

RUN mkdir -p /app/scholarspace
WORKDIR /app/scholarspace

ENV PATH="/app/scholarspace:$PATH" \
RAILS_ROOT="/app/scholarspace" \
RAILS_SERVE_STATIC_FILES="1" \
LD_PRELOAD="/usr/local/lib/libjemalloc.so.2" 

COPY --chown=8983:8983 Gemfile Gemfile.lock ./

RUN bundle config set deployment true 

RUN bundle install

COPY --chown=8983:8983 . ./

COPY --chmod=755 ./bin/scholarspace-entrypoint-dev.sh ./

FROM scholarspace-dev-base AS scholarspace-dev

ENTRYPOINT ["./scholarspace-entrypoint-dev.sh"]
ONBUILD RUN RAILS_ENV=development SECRET_KEY_BASE=`bin/rake secret` bundle exec rake assets:precompile
CMD ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0", "RAILS_ENV=development"]

FROM scholarspace-dev-base AS scholarspace-dev-worker

USER root
RUN apk --no-cache add bash \
  ffmpeg \
  mediainfo \
  perl \
  tesseract-ocr
USER 8983:8983

CMD ["bundle", "exec", "sidekiq", "RAILS_ENV=development"]
