# Requires Docker Compose v2
name: scholarspace
services:
  rails:
    container_name: rails
    hostname: rails
    build:
      context: .
      target: scholarspace
      args:
        - EXTRA_APK_PACKAGES=git less
        - BUNDLE_GEMFILE=Gemfile
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    stdin_open: true
    tty: true
    user: root
    env_file:
      - .env
    environment:
      - RAILS_ROOT=/app/scholarspace
      - SECRET_KEY_BASE_DUMMY=1
      - RAILS_ENV=production
      - SEED_SCHOLARSPACE=true
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - scholarspace-storage:/app/scholarspace/storage
      - scholarspace-derivatives:/app/scholarspace/derivatives
      - scholarspace-uploads:/app/scholarspace/uploads
      - scholarspace-public:/app/scholarspace/public
      - scholarspace-tmp:/app/scholarspace/tmp
    networks:
      - scholarspace

  worker:
    container_name: worker
    build:
      context: .
      target: scholarspace-worker
      args:
        - EXTRA_APK_PACKAGES=git less
        - BUNDLE_GEMFILE=Gemfile
    command: sh -c 'bundle exec sidekiq'
    user: root
    env_file:
      - .env
    environment:
      - RAILS_ROOT=/app/scholarspace
      - SECRET_KEY_BASE_DUMMY=1
      - RAILS_ENV=production
    depends_on:
      - fits
      - postgres
      - redis
      - solr
    volumes:
      - scholarspace-storage:/app/scholarspace/storage
      - scholarspace-derivatives:/app/scholarspace/derivatives
      - scholarspace-uploads:/app/scholarspace/uploads
      - scholarspace-public:/app/scholarspace/public
      - scholarspace-tmp:/app/scholarspace/tmp
    networks:
      - scholarspace
  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl
    restart: unless-stopped
    depends_on:
      - rails
    networks:
      - scholarspace

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - scholarspace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$DB_NAME -U $$DB_USERNAME"]
      interval: 30s
      timeout: 5s
      retries: 20

  fits:
    container_name: fits
    image: ghcr.io/samvera/fitsservlet:1.6.0
    networks:
      - scholarspace
  
  redis:
    container_name: redis
    image: bitnami/redis:6.2
    env_file:
      - .env
    volumes:
      - redis:/bitnami/redis/data
    networks:
      - scholarspace
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  solr:
    container_name: solr
    image: solr:8.11
    command:
      - sh
      - "-c"
      - "precreate-core scholarspace-test /opt/solr/server/configsets/scholarspaceconf; solr-precreate scholarspace /opt/solr/server/configsets/scholarspaceconf"
    volumes:
      - solr_home:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/scholarspaceconf
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    networks:
      - scholarspace
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider --tries=1 localhost:8983 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 20

volumes:
  db:
  scholarspace-storage:
  scholarspace-derivatives:
  scholarspace-uploads:
  scholarspace-public:
  scholarspace-tmp:
  redis:
  solr_home:
networks:
  scholarspace:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-scholarspace