# frozen_string_literal: true

# Generated by hyrax:listeners
#
# The Hyrax engine uses a publish/subscribe programming model to allow
# pluggable behavior in response to certain repository events. A range of events
# are published on a topic based event bus.
#
# This listener provides a template.
#
# For simple use cases, it's fine to add behavior to the `#on_*` methods in this
# Listener. If you have more than trivial behavior here, you probably want to add
# new classes that are named narrowly scoped and named for what the listener is
# for.
#
# When writing listener methods, it's important to carefully consider error,
# handling. Unhandled exceptions short-circuit behavior for other listeners,
# so it's a good idea to be paying attention to failure cases.
#
# @see https://github.com/samvera/hyrax/wiki/Hyrax's-Event-Bus-(Hyrax::Publisher)
# @see https://www.rubydoc.info/gems/hyrax/Hyrax/Publisher
# @see https://dry-rb.org/gems/dry-events
class HyraxListener

  def self.derivatives_enqueue_debounce
    @derivatives_enqueue_debounce ||= DerivativeJobSettings.seconds(:waits, :hyrax_listener, :orchestrate_debounce_seconds).seconds
  end

  def self.orchestrate_enqueue_wait
    @orchestrate_enqueue_wait ||= DerivativeJobSettings.seconds(:waits, :hyrax_listener, :orchestrate_enqueue_wait_seconds).seconds
  end

  # def on_batch_created
  # end

  # def on_collection_deleted
  # end

  # def on_collection_metadata_updated
  # end

  # def on_collection_membership_update
  # end

  def on_file_characterized(event)
    file_set = event[:file_set]
    unless file_set
      Rails.logger.warn('derivative_orchestration_skipped reason=missing_file_set')
      return
    end

    # get the parent work
    work = Hyrax.custom_queries.find_parent_work(resource: file_set)
    unless work
      Rails.logger.warn("derivative_orchestration_skipped reason=missing_parent_work file_set_id=#{file_set.id}")
      return
    end

    # bail if it is a service file to avoid 
    # recursive derivative generation. 
    if file_set.service_file
      Rails.logger.info("derivative_orchestration_skipped reason=service_file work_id=#{work.id} file_set_id=#{file_set.id}")
      return
    end

    if derivatives_enqueue_debounced?(work.id.to_s)
      Rails.logger.info("derivative_orchestration_skipped reason=debounced work_id=#{work.id} file_set_id=#{file_set.id}")
      return
    end

    job = DerivativeJobs::WorkLevel::OrchestrateJob.set(wait: self.class.orchestrate_enqueue_wait).perform_later(
      work_id: work.id.to_s
    )
    Rails.logger.info(
      "derivative_orchestration_enqueued work_id=#{work.id} file_set_id=#{file_set.id} " \
      "job_id=#{job.job_id} queue=#{job.queue_name}"
    )
  rescue StandardError => error
    Rails.logger.error(
      "derivative_orchestration_enqueue_failed work_id=#{work&.id} file_set_id=#{file_set&.id} " \
      "error_class=#{error.class} error_message=#{error.message}"
    )
    nil
  end

  # def on_file_downloaded
  # end

  # def on_file_metadata_updated
  # end

  # def on_file_metadata_deleted
  # end

  # def on_file_uploaded
  # end

  # def on_file_set_audited
  # end

  # def on_file_set_attached
  # end

  # def on_file_set_url_imported
  # end

  # def on_file_set_restored
  # end

  # def on_object_deleted
  # end

  # def on_object_failed_deposit
  # end

  # def on_object_deposited
  # end

  # def on_object_acl_updated
  # end

  # def on_object_membership_updated
  # end

  # def on_object_metadata_updated
  # end

  private

  def derivatives_enqueue_debounced?(work_id)
    cache_key = "derivatives:orchestration:scheduled:#{work_id}"
    already_scheduled = Sidekiq.redis { |r| r.set(cache_key, 1, nx: true, ex: self.class.derivatives_enqueue_debounce.to_i) }
    !already_scheduled
  end
end
