# frozen_string_literal: true

# Generated by hyrax:listeners
#
# The Hyrax engine uses a publish/subscribe programming model to allow
# pluggable behavior in response to certain repository events. A range of events
# are published on a topic based event bus.
#
# This listener provides a template.
#
# For simple use cases, it's fine to add behavior to the `#on_*` methods in this
# Listener. If you have more than trivial behavior here, you probably want to add
# new classes that are named narrowly scoped and named for what the listener is
# for.
#
# When writing listener methods, it's important to carefully consider error,
# handling. Unhandled exceptions short-circuit behavior for other listeners,
# so it's a good idea to be paying attention to failure cases.
#
# @see https://github.com/samvera/hyrax/wiki/Hyrax's-Event-Bus-(Hyrax::Publisher)
# @see https://www.rubydoc.info/gems/hyrax/Hyrax/Publisher
# @see https://dry-rb.org/gems/dry-events
class HyraxListener
  DERIVATIVES_ENQUEUE_DEBOUNCE = 5.minutes

  # def on_batch_created
  # end

  # def on_collection_deleted
  # end

  # def on_collection_metadata_updated
  # end

  # def on_collection_membership_update
  # end

  def on_file_characterized(event)
    file_set = event[:file_set]
    return unless file_set

    # get the parent work
    work = Hyrax.custom_queries.find_parent_work(resource: file_set)
    return unless work

    # bail if it is a service file to avoid 
    # recursive derivative generation. 
    return if file_set.service_file

    return if derivatives_enqueue_debounced?(work.id.to_s)

    DerivativeJobs::WorkLevel::Coordinator::OrchestrateJob.set(wait: 2.minutes).perform_later(
      work_id: work.id.to_s
    )
  rescue StandardError
    # if something breaks in custom derivative process, let others process
    nil
  end

  # def on_file_downloaded
  # end

  # def on_file_metadata_updated
  # end

  # def on_file_metadata_deleted
  # end

  # def on_file_uploaded
  # end

  # def on_file_set_audited
  # end

  # def on_file_set_attached
  # end

  # def on_file_set_url_imported
  # end

  # def on_file_set_restored
  # end

  # def on_object_deleted
  # end

  # def on_object_failed_deposit
  # end

  # def on_object_deposited
  # end

  # def on_object_acl_updated
  # end

  # def on_object_membership_updated
  # end

  # def on_object_metadata_updated
  # end

  private

  def derivatives_enqueue_debounced?(work_id)
    cache_key = "derivatives:orchestration:scheduled:#{work_id}"
    already_scheduled = Sidekiq.redis { |r| r.set(cache_key, 1, nx: true, ex: DERIVATIVES_ENQUEUE_DEBOUNCE.to_i) }
    !already_scheduled
  end
end
