---
:queues:
  - [ingest, 4]
  - [batch, 2]
  - [derivatives_pdf_to_images, 1]
  - [derivatives_images_to_pdf, 1]
  - [derivatives_audio_transcript, 1]
  - [derivatives_thumbnail, 1]
  - [derivatives_pdf_hocr_embedding, 1]
  - [default, 1]

test:
  :concurrency: 1

development:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 1 %>
  :logfile: ./log/sidekiq_development.log

production:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 4 %>
