---
# allows for splitting of jobs into seperate sidekiq containers, with one just for whisper audio transcription
<%
only_audio_transcript = ENV['SIDEKIQ_ONLY_AUDIO_TRANSCRIPT'] == 'true'
only_pdf_text_extraction = ENV['SIDEKIQ_ONLY_PDF_TEXT_EXTRACTION'] == 'true'
%>

:queues:
<% if only_audio_transcript %>
  - [audio_transcript, 1]
<% elsif only_pdf_text_extraction %>
  - [pdf_text_extraction, 1]
<% else %>
  - [ingest, 4]
  - [batch, 2]
  - [pdf_to_images, 1]
  - [images_to_pdf, 1]
  - [thumbnail, 1]
  - [default, 1]
<% end %>

test:
  :concurrency: 1

development:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 1 %>
  :logfile: ./log/sidekiq_development.log

production:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 4 %>
