development:
  url: <%= ENV['SOLR_DEV_URL'] || "http://127.0.0.1:8983/solr/scholarspace-dev" %>
test: &test
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8983/solr/scholarspace-test" %>
production:
  url: <%= ENV['SOLR_PROD_URL'] || "http://127.0.0.1:8983/solr/scholarspace-prod" %>
