name: CI

on:
  # allow running action manually
  workflow_dispatch:

  # trigger on pull request to either main or staging branches
  pull_request:
    branches:
      - main
      - staging
      - ci-test
# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
     # Checkout the repository code
      - name: Check out repository code
        uses: actions/checkout@v4
      # Copy the pre-filled example.dev.env file to use as the dev.env file for testing
      - name: cd to scholarspace folder
        run : |
          cd /home/runner/work/scholarspace-5-test/scholarspace-5-test
      - name: Create env file
        run: |
          cp example.dev.env dev.env
       # Start all of the docker containers and wait until positive response from healthchecks
      - name: Start Docker containers
        run: ./bin/test
        
